services:
  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: "testdb"
      JWT_SECRET: f695fdc9433b8812e973e4372e01a64119192cb259e8804a38daab77b84ff8a2fe6baa11956316e0698ed2116b45421497b92c469de1c8b8be69fa38c8b0cc27
      JWT_REFRESH_SECRET: b75630645013602b03881b1da07110a5db50efadee04d723a1d94aa3b4020af22b8373f813f68c7c137941fa85f131d2c509a7291aa4579736d1e378f23cef5c

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
