FROM node:16.0.0 as build

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

#---

FROM node:16.0.0

WORKDIR /app

ENV NODE_ENV=16.0.0

COPY package.json .
COPY yarn.lock .
COPY ormconfig.js .

RUN yarn install

COPY --from=build /app/dist ./dist

EXPOSE 5000

ENTRYPOINT [ "yarn", "start:prod" ]